import Head from "next/head";
import { Html } from "next/document";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      {/* <Head> */}
      {/* <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
        rel="stylesheet"
      /> */}
      {/* </Head> */}
      <body className="font-sans">{children}</body>
    </html>
  );
};

export default RootLayout;
